version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile-client
    volumes:
      - ./client:/client
    tty: true
    ports:
      - 3000:3000